/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { DividerProps, GridProps, HeadingProps, SwitchFieldProps, TextFieldProps } from "@aws-amplify/ui-react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type ChildrenPreferenceInputValues = {
    InfantBoy?: boolean;
    InfantBoyNum?: number;
    InfantGirl?: boolean;
    InfantGirlNum?: number;
    InfantNoPref?: boolean;
    InfantNoPrefNum?: number;
    ElementaryBoy?: boolean;
    ElementaryBoyNum?: number;
    ElementaryGirl?: boolean;
    ElementaryGirlNum?: number;
    ElementaryNoPref?: boolean;
    ElementaryNoPrefNum?: number;
    MiddleSchoolBoy?: boolean;
    MiddleSchoolBoyNum?: number;
    MiddleSchoolGirl?: boolean;
    MiddleSchoolGirlNum?: number;
    MiddleSchoolNoPref?: boolean;
    MiddleSchoolNumNoPref?: number;
    HighSchoolBoy?: boolean;
    HighSchoolBoyNum?: number;
    HighSchoolGirl?: boolean;
    HighSchoolGirlNum?: number;
    HighSchoolNoPref?: boolean;
    HighSchoolNoPrefNum?: number;
    AgingOutBoy?: boolean;
    AgingOutBoyNum?: number;
    AgingOutGirl?: boolean;
    AgingOutGirlNum?: number;
    AgingOutNoPref?: boolean;
    AgingOutNoPrefNum?: number;
    NoPrefBoy?: boolean;
    NoPrefBoyNum?: number;
    NoPrefGirl?: boolean;
    NoPrefGirlNum?: number;
    NoPref?: boolean;
    NoPrefNum?: number;
    TotalNumChildren?: number;
};
export declare type ChildrenPreferenceValidationValues = {
    InfantBoy?: ValidationFunction<boolean>;
    InfantBoyNum?: ValidationFunction<number>;
    InfantGirl?: ValidationFunction<boolean>;
    InfantGirlNum?: ValidationFunction<number>;
    InfantNoPref?: ValidationFunction<boolean>;
    InfantNoPrefNum?: ValidationFunction<number>;
    ElementaryBoy?: ValidationFunction<boolean>;
    ElementaryBoyNum?: ValidationFunction<number>;
    ElementaryGirl?: ValidationFunction<boolean>;
    ElementaryGirlNum?: ValidationFunction<number>;
    ElementaryNoPref?: ValidationFunction<boolean>;
    ElementaryNoPrefNum?: ValidationFunction<number>;
    MiddleSchoolBoy?: ValidationFunction<boolean>;
    MiddleSchoolBoyNum?: ValidationFunction<number>;
    MiddleSchoolGirl?: ValidationFunction<boolean>;
    MiddleSchoolGirlNum?: ValidationFunction<number>;
    MiddleSchoolNoPref?: ValidationFunction<boolean>;
    MiddleSchoolNumNoPref?: ValidationFunction<number>;
    HighSchoolBoy?: ValidationFunction<boolean>;
    HighSchoolBoyNum?: ValidationFunction<number>;
    HighSchoolGirl?: ValidationFunction<boolean>;
    HighSchoolGirlNum?: ValidationFunction<number>;
    HighSchoolNoPref?: ValidationFunction<boolean>;
    HighSchoolNoPrefNum?: ValidationFunction<number>;
    AgingOutBoy?: ValidationFunction<boolean>;
    AgingOutBoyNum?: ValidationFunction<number>;
    AgingOutGirl?: ValidationFunction<boolean>;
    AgingOutGirlNum?: ValidationFunction<number>;
    AgingOutNoPref?: ValidationFunction<boolean>;
    AgingOutNoPrefNum?: ValidationFunction<number>;
    NoPrefBoy?: ValidationFunction<boolean>;
    NoPrefBoyNum?: ValidationFunction<number>;
    NoPrefGirl?: ValidationFunction<boolean>;
    NoPrefGirlNum?: ValidationFunction<number>;
    NoPref?: ValidationFunction<boolean>;
    NoPrefNum?: ValidationFunction<number>;
    TotalNumChildren?: ValidationFunction<number>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type ChildrenPreferenceOverridesProps = {
    ChildrenPreferenceGrid?: PrimitiveOverrideProps<GridProps>;
    SectionalElement12?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement0?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement3?: PrimitiveOverrideProps<DividerProps>;
    RowGrid3?: PrimitiveOverrideProps<GridProps>;
    InfantBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    InfantBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid4?: PrimitiveOverrideProps<GridProps>;
    InfantGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    InfantGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid5?: PrimitiveOverrideProps<GridProps>;
    InfantNoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    InfantNoPrefNum?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement1?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement2?: PrimitiveOverrideProps<DividerProps>;
    RowGrid8?: PrimitiveOverrideProps<GridProps>;
    ElementaryBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    ElementaryBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid9?: PrimitiveOverrideProps<GridProps>;
    ElementaryGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    ElementaryGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid10?: PrimitiveOverrideProps<GridProps>;
    ElementaryNoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    ElementaryNoPrefNum?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement4?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement5?: PrimitiveOverrideProps<DividerProps>;
    RowGrid13?: PrimitiveOverrideProps<GridProps>;
    MiddleSchoolBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    MiddleSchoolBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid14?: PrimitiveOverrideProps<GridProps>;
    MiddleSchoolGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    MiddleSchoolGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid15?: PrimitiveOverrideProps<GridProps>;
    MiddleSchoolNoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    MiddleSchoolNumNoPref?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement6?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement7?: PrimitiveOverrideProps<DividerProps>;
    RowGrid18?: PrimitiveOverrideProps<GridProps>;
    HighSchoolBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    HighSchoolBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid19?: PrimitiveOverrideProps<GridProps>;
    HighSchoolGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    HighSchoolGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid20?: PrimitiveOverrideProps<GridProps>;
    HighSchoolNoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    HighSchoolNoPrefNum?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement8?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement9?: PrimitiveOverrideProps<DividerProps>;
    RowGrid23?: PrimitiveOverrideProps<GridProps>;
    AgingOutBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    AgingOutBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid24?: PrimitiveOverrideProps<GridProps>;
    AgingOutGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    AgingOutGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid25?: PrimitiveOverrideProps<GridProps>;
    AgingOutNoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    AgingOutNoPrefNum?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement10?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement11?: PrimitiveOverrideProps<DividerProps>;
    RowGrid28?: PrimitiveOverrideProps<GridProps>;
    NoPrefBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    NoPrefBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid29?: PrimitiveOverrideProps<GridProps>;
    NoPrefGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    NoPrefGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid30?: PrimitiveOverrideProps<GridProps>;
    NoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    NoPrefNum?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement13?: PrimitiveOverrideProps<DividerProps>;
    TotalNumChildren?: PrimitiveOverrideProps<TextFieldProps>;
} & EscapeHatchProps;
export declare type ChildrenPreferenceProps = React.PropsWithChildren<{
    overrides?: ChildrenPreferenceOverridesProps | undefined | null;
} & {
    clearOnSuccess?: boolean;
    onSubmit?: (fields: ChildrenPreferenceInputValues) => ChildrenPreferenceInputValues;
    onSuccess?: (fields: ChildrenPreferenceInputValues) => void;
    onError?: (fields: ChildrenPreferenceInputValues, errorMessage: string) => void;
    onChange?: (fields: ChildrenPreferenceInputValues) => ChildrenPreferenceInputValues;
    onValidate?: ChildrenPreferenceValidationValues;
} & React.CSSProperties>;
export default function ChildrenPreference(props: ChildrenPreferenceProps): React.ReactElement;
