/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { GridProps, SwitchFieldProps, TextFieldProps } from "@aws-amplify/ui-react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type SponsorPreferencesCreateFormInputValues = {
    InfantBoy?: boolean;
    InfantGirl?: boolean;
    InfantNoPref?: boolean;
    InfantBoyNum?: number;
    InfantGirlNum?: number;
    InfantNoPrefNum?: number;
    ElementaryBoy?: boolean;
    ElementaryGirl?: boolean;
    ElementaryNoPref?: boolean;
    ElementaryBoyNum?: number;
    ElementaryGirlNum?: number;
    ElementaryNoPrefNum?: number;
    MiddleSchoolBoy?: boolean;
    MiddleSchoolGirl?: boolean;
    MiddleSchoolNoPref?: boolean;
    MiddleSchoolBoyNum?: number;
    MiddleSchoolGirlNum?: number;
    MiddleSchoolNumNoPref?: number;
    HighSchoolBoy?: boolean;
    HighSchoolGirl?: boolean;
    HighSchoolNoPref?: boolean;
    HighSchoolBoyNum?: number;
    HighSchoolGirlNum?: number;
    HighSchoolNoPrefNum?: number;
    AgingOutBoy?: boolean;
    AgingOutGirl?: boolean;
    AgingOutNoPref?: boolean;
    AgingOutBoyNum?: number;
    AgingOutGirlNum?: number;
    AgingOutNoPrefNum?: number;
    NoPrefBoy?: boolean;
    NoPrefGirl?: boolean;
    NoPref?: boolean;
    NoPrefBoyNum?: number;
    NoPrefGirlNum?: number;
    NoPrefNum?: number;
    TotalNumChildren?: number;
};
export declare type SponsorPreferencesCreateFormValidationValues = {
    InfantBoy?: ValidationFunction<boolean>;
    InfantGirl?: ValidationFunction<boolean>;
    InfantNoPref?: ValidationFunction<boolean>;
    InfantBoyNum?: ValidationFunction<number>;
    InfantGirlNum?: ValidationFunction<number>;
    InfantNoPrefNum?: ValidationFunction<number>;
    ElementaryBoy?: ValidationFunction<boolean>;
    ElementaryGirl?: ValidationFunction<boolean>;
    ElementaryNoPref?: ValidationFunction<boolean>;
    ElementaryBoyNum?: ValidationFunction<number>;
    ElementaryGirlNum?: ValidationFunction<number>;
    ElementaryNoPrefNum?: ValidationFunction<number>;
    MiddleSchoolBoy?: ValidationFunction<boolean>;
    MiddleSchoolGirl?: ValidationFunction<boolean>;
    MiddleSchoolNoPref?: ValidationFunction<boolean>;
    MiddleSchoolBoyNum?: ValidationFunction<number>;
    MiddleSchoolGirlNum?: ValidationFunction<number>;
    MiddleSchoolNumNoPref?: ValidationFunction<number>;
    HighSchoolBoy?: ValidationFunction<boolean>;
    HighSchoolGirl?: ValidationFunction<boolean>;
    HighSchoolNoPref?: ValidationFunction<boolean>;
    HighSchoolBoyNum?: ValidationFunction<number>;
    HighSchoolGirlNum?: ValidationFunction<number>;
    HighSchoolNoPrefNum?: ValidationFunction<number>;
    AgingOutBoy?: ValidationFunction<boolean>;
    AgingOutGirl?: ValidationFunction<boolean>;
    AgingOutNoPref?: ValidationFunction<boolean>;
    AgingOutBoyNum?: ValidationFunction<number>;
    AgingOutGirlNum?: ValidationFunction<number>;
    AgingOutNoPrefNum?: ValidationFunction<number>;
    NoPrefBoy?: ValidationFunction<boolean>;
    NoPrefGirl?: ValidationFunction<boolean>;
    NoPref?: ValidationFunction<boolean>;
    NoPrefBoyNum?: ValidationFunction<number>;
    NoPrefGirlNum?: ValidationFunction<number>;
    NoPrefNum?: ValidationFunction<number>;
    TotalNumChildren?: ValidationFunction<number>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type SponsorPreferencesCreateFormOverridesProps = {
    SponsorPreferencesCreateFormGrid?: PrimitiveOverrideProps<GridProps>;
    InfantBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    InfantGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    InfantNoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    InfantBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    InfantGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    InfantNoPrefNum?: PrimitiveOverrideProps<TextFieldProps>;
    ElementaryBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    ElementaryGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    ElementaryNoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    ElementaryBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    ElementaryGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    ElementaryNoPrefNum?: PrimitiveOverrideProps<TextFieldProps>;
    MiddleSchoolBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    MiddleSchoolGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    MiddleSchoolNoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    MiddleSchoolBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    MiddleSchoolGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    MiddleSchoolNumNoPref?: PrimitiveOverrideProps<TextFieldProps>;
    HighSchoolBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    HighSchoolGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    HighSchoolNoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    HighSchoolBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    HighSchoolGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    HighSchoolNoPrefNum?: PrimitiveOverrideProps<TextFieldProps>;
    AgingOutBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    AgingOutGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    AgingOutNoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    AgingOutBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    AgingOutGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    AgingOutNoPrefNum?: PrimitiveOverrideProps<TextFieldProps>;
    NoPrefBoy?: PrimitiveOverrideProps<SwitchFieldProps>;
    NoPrefGirl?: PrimitiveOverrideProps<SwitchFieldProps>;
    NoPref?: PrimitiveOverrideProps<SwitchFieldProps>;
    NoPrefBoyNum?: PrimitiveOverrideProps<TextFieldProps>;
    NoPrefGirlNum?: PrimitiveOverrideProps<TextFieldProps>;
    NoPrefNum?: PrimitiveOverrideProps<TextFieldProps>;
    TotalNumChildren?: PrimitiveOverrideProps<TextFieldProps>;
} & EscapeHatchProps;
export declare type SponsorPreferencesCreateFormProps = React.PropsWithChildren<{
    overrides?: SponsorPreferencesCreateFormOverridesProps | undefined | null;
} & {
    clearOnSuccess?: boolean;
    onSubmit?: (fields: SponsorPreferencesCreateFormInputValues) => SponsorPreferencesCreateFormInputValues;
    onSuccess?: (fields: SponsorPreferencesCreateFormInputValues) => void;
    onError?: (fields: SponsorPreferencesCreateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: SponsorPreferencesCreateFormInputValues) => SponsorPreferencesCreateFormInputValues;
    onValidate?: SponsorPreferencesCreateFormValidationValues;
} & React.CSSProperties>;
export default function SponsorPreferencesCreateForm(props: SponsorPreferencesCreateFormProps): React.ReactElement;
